### ISSUE TITLE
Scrape more than the first page of each subreddit

### ISSUE THREAD

**Issue by itsmais** [itsmais/word-cloud-subreddit#1]
This code currently fetches the main page of the given subreddit (link + "json"). It would be nice to scrape older pages so that the word cloud is richer with words and their frequencies.

**Comment by ps9793** [comment]
Hey @itsmais ,
How deep would you like the scrape to be ?
Because it can potentially go on till the end of the subreddit and that might affect performance

Right now, the front page scrape returns about 25-30 children
Would increasing this to 100 children, be sufficient ?

**Comment by itsmais** [comment]
Hello @ps9793!
Thanks for your comment.
Sure, 100 children sounds like a great number! 
Looking forward!

**Comment by ps9793** [comment]
@itsmais , I just added a PR for this issue. Kindly check and let me know if everything is working as you expected it to.

**Comment by ps9793** [comment]
Also, can you please add the `hacktoberfest` tag as it will help me with the t-shirt thing.
