### ISSUE TITLE
Replace the colors with CSS variables

### ISSUE THREAD

**Issue by itsmais** [itsmais/word-cloud-subreddit#12]
There's only one stylesheet and it's quite short. It would be nice to have all the current colors replaced with CSS variables so they're easily changed in the future.

For guidance on CSS variables, please check https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties

**Comment by ramonvheerde** [comment]
Can you assign this one to me?

**Comment by Sagargajare** [comment]
@itsmais I would like to contribute to this project.  Can you assign it to me?

**Comment by itsmais** [comment]
hello @Sagargajare ! I'm sorry but @ramonvheerde has already resolved the issue in this [PR](https://github.com/itsmais/word-cloud-subreddit/pull/13) (thanks a lot @ramonvheerde 🚀).

I'm closing this issue. Please feel free to further discover the project and work on something that you think is an enhancement. 

Thank you and have a good day!
