### ISSUE TITLE
Add dark mode switch to the web page

### ISSUE THREAD

**Issue by itsmais** [itsmais/word-cloud-subreddit#14]
The new colors don't matter; you can pick anything you want for now. We can change that later. What matters now is having the functionality of theme switching.

The button could be something like: https://dribbble.com/shots/10492788-Toggle-animation-Light-Dark-theme but it doesn't have to be as complicated/animated.

**Comment by Sagargajare** [comment]
@itsmais I would like to contribute in this feature

**Comment by Sagargajare** [comment]
Can you assign it to me?

**Comment by itsmais** [comment]
of course @Sagargajare . Let me know if you need something.
