### ISSUE TITLE
Eliminate the linking keywords (the, and, a, an, etc.)

### ISSUE THREAD

**Issue by itsmais** [itsmais/word-cloud-subreddit#2]
The dictionary of occurrences currently has all words and does no filtering whatsoever. It would be nice to eliminate the linking English words like the, and, a, an etc.

**Comment by varadpoddar** [comment]
Can I work on this issue, please?

**Comment by itsmais** [comment]
> Can I work on this issue, please?

Sure, go ahead!

**Comment by varadpoddar** [comment]
I currently have the following words in my list of words to filter 
"the", "and", "a", "an"
Are there any other words you'd like to filter?

**Comment by itsmais** [comment]
> I currently have the following words in my list of words to filter
> "the", "and", "a", "an"
> Are there any other words you'd like to filter?

maybe punctuation? i.e. commas, apostrophes, &'s, quotes and question marks.
what do you think?

**Comment by varadpoddar** [comment]
Ty for the feedback. It was an oversight on my part.
I'll fork the repo and work on the issues and test before resubmitting. :)
