### ISSUE TITLE
Eliminate linking keywords, their capital cases and punctuations.

### ISSUE THREAD

**Issue by itsmais** [itsmais/word-cloud-subreddit#4]
We're currently checking for `"the",",",".","&","AND","And","A","An","The","with","to", "To", "and","for","For", "a", "an"` but that's obviously not nice. We should have the main keywords in one list, and punctuations in a different one. We should also check for the capital cases of words.

**Comment by shobhi1310** [comment]
Ma'am is this issue open, can I work on this ?

**Comment by itsmais** [comment]
> Ma'am is this issue open, can I work on this ?

Hello! Sure, go on!
Thank you.

**Comment by shobhi1310** [comment]
Is this the change required? 
And how will the stop_words list be extended because for now, it is very limited and not capturing the most commonly occurring words.

And do review my PR once @itsmais

**Comment by varadpoddar** [comment]
I think the code can be further improved by converting each word to lowercase and checking against the filter list. Moreover, we can reduce the punctuation check to a regular expression that would eliminate the need to store punctuations as a list. 

Would you mind if I worked on that @itsmais?

**Comment by itsmais** [comment]
of course not @varadpoddar, please go ahead!
